# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: homework.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ehomework.proto\")\n\x07Players\x12\x1e\n\x07players\x18\x01 \x03(\x0b\x32\r.PlayerObject\"_\n\x0cPlayerObject\x12\x10\n\x08nickname\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x15\n\rdate_of_birth\x18\x03 \x01(\t\x12\n\n\x02xp\x18\x04 \x01(\x05\x12\x0b\n\x03\x63ls\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'homework_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PLAYERS']._serialized_start=18
  _globals['_PLAYERS']._serialized_end=59
  _globals['_PLAYEROBJECT']._serialized_start=61
  _globals['_PLAYEROBJECT']._serialized_end=156
# @@protoc_insertion_point(module_scope)
